'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';
import { OrderItem } from '@/src/domain/entity/order-item.entity';
import { Book } from '@/src/domain/entity/book.entity';
import { Voucher } from '@/src/domain/entity/voucher.entity';
import { DiscountType } from '@/src/domain/entity/discount-type.enum';

interface CartContextType {
  cart: OrderItem[];
  addToCart: (product: Book, amount: number) => void;
  removeFromCart: (productId: number) => void;
  updateAmount: (productId: number, amount: number) => void;
  clearCart: () => void;
  cartTotal: number;
  cartCount: number;
  voucherDiscount: number;
  appliedVoucher: Voucher | null;
  applyVoucher: (voucher: Voucher) => void;
  removeVoucher: () => void;
}

const CartContext = createContext<CartContextType | undefined>(undefined);

export const CartProvider = ({ children }: { children: React.ReactNode }) => {
  const [cart, setCart] = useState<OrderItem[]>([]);

  // Load cart from localStorage on mount
  useEffect(() => {
    const savedCart = localStorage.getItem('bookshop_cart');
    // eslint-disable-next-line react-hooks/set-state-in-effect
    if (savedCart) setCart(JSON.parse(savedCart));
  }, []);

  // Save cart to localStorage whenever it changes
  useEffect(() => {
    localStorage.setItem('bookshop_cart', JSON.stringify(cart));
  }, [cart]);

  const addToCart = (product: Book, amount: number) => {
    console.log(`Adding to cart: ${product.title} (x${amount})`);

    setCart((prev) => {
      // 1. Correct the 'find' logic: 
      // We check item.book.id because OrderItem stores the product inside 'book'
      const existing = prev.find((item) => item.book.id === product.id);

      if (existing) {
        return prev.map((item) =>
          item.book.id === product.id
            ? { ...item, quantity: item.quantity + amount } // Use 'quantity', not 'amount'
            : item
        );
      }

      // 2. Correct the 'new item' structure:
      // This must match the OrderItem interface exactly
      const newItem: OrderItem = {
        book: product,             // The entire Book entity
        quantity: amount,          // Matches 'quantity' field
        unitPrice: product.price,  // Matches 'unitPrice' field
        discount: product.discount || 0,
        // id is omitted/undefined as it's generated by Spring Boot later
      };

      return [...prev, newItem];
    });
  };

  const removeFromCart = (productId: number) => {
    setCart((prev) => prev.filter((item) => item.id !== productId));
  };

  const updateAmount = (productId: number, amount: number) => {
    setCart((prev) =>
      prev.map((item) =>
        item.id === productId ? { ...item, amount } : item
      )
    );
  };

  const clearCart = () => setCart([]);

  const cartCount = cart.reduce((acc, item) => acc + item.quantity, 0);

  const [appliedVoucher, setAppliedVoucher] = useState<Voucher | null>(null);

  const applyVoucher = (voucher: Voucher) => setAppliedVoucher(voucher);
  const removeVoucher = () => setAppliedVoucher(null);

  // Update cartTotal calculation logic:
  const total = cart.reduce((acc, item) => {
    const price = item.discount ? item.unitPrice * (1 - item.discount / 100) : item.unitPrice;
    return acc + price * item.quantity;
  }, 0);

  // New: Calculate discount from voucher
  const voucherDiscount = appliedVoucher
    ? (appliedVoucher.discountType === DiscountType.PERCENTAGE
      ? (total * appliedVoucher.discountValue / 100)
      : appliedVoucher.discountValue)
    : 0;

  const finalCartTotal = Math.max(0, total - voucherDiscount);

  return (
    <CartContext.Provider value={{ cart, addToCart, removeFromCart, updateAmount, clearCart, cartTotal: finalCartTotal, cartCount, voucherDiscount, appliedVoucher, applyVoucher, removeVoucher }}>
      {children}
    </CartContext.Provider>
  );
};

export const useCart = () => {
  const context = useContext(CartContext);
  if (!context) throw new Error('useCart must be used within a CartProvider');
  return context;
};